#!/bin/sh

usage="\
Usage: libart2-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--libs] [--cflags]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

if ! which pkg-config >/dev/null; then
    echo "pkg-config not found on your system" 1>&2
    exit 1
fi

prefix=`pkg-config --variable=prefix libart-2.0`
exec_prefix=`pkg-config --variable=exec_prefix libart-2.0`
exec_prefix_set=no
libs=""
output_libs=no

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix=*)
      prefix=$optarg
      if test $exec_prefix_set = no ; then
        exec_prefix=$optarg
      fi
      ;;
    --prefix)
      echo $prefix
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      exec_prefix_set=yes
      ;;
    --exec-prefix)
      echo $exec_prefix
      ;;
    --version)
      echo `pkg-config --modversion libart-2.0`
      ;;
    --cflags)
      echo `pkg-config --cflags-only-I libart-2.0`
      ;;
    --libs)
      libs=`pkg-config --libs libart-2.0`
      output_libs=yes
      ;;
    --static)
      libs="$libs -lm"
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done

if test $output_libs = yes ; then
    echo $libs
fi
